# # A simple example of ClusterConfig object:
# ---
# apiVersion: eksctl.io/v1alpha5
# kind: ClusterConfig

# metadata:
#   name: cluster-1
#   region: eu-north-1

# nodeGroups:
#   - name: ng-1
#     instanceType: m5.large
#     desiredCapacity: 1


apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: expense
  region: us-east-1

managedNodeGroups:
  - name: expense
    instanceTypes: ["m5.large", "c3.large","c4.large","c5.large"]
    desiredCapacity: 3
    spot: true